### ISSUE TITLE
[BUG] CVTArchive mishandles its "bins" parameter

### ISSUE THREAD

**Issue by twoletters** [icaros-usc/pyribs#174]
- pyribs version: 0.4.0
- Python version: 3.6.9, 3.8.3
- Operating System: Ubuntu 18.04.5 LTS, MacOS 10.15.7

### Description

Parameter `bins` of the CVTArchive constructor is incorrectly cast into a tuple, causing `np.zeros` to reject it as a parameter later on.

### Steps to Reproduce

```
import ribs, numpy as np
archive = ribs.archives.CVTArchive((5, 5, 5, 5, 5), ((0., 1.), (0., 1.), (0., 1.), (0., 1.), (0., 1.)))
print("There be dragons: ", archive._storage_dims)
# Prints: There be dragons: ((5, 5, 5, 5, 5),)
emitters = [ribs.emitters.ImprovementEmitter(archive, np.zeros(5), .5, seed=0, batch_size=20)]
optimizer = ribs.optimizers.Optimizer(archive, emitters)
# This crash ensues:
#  Traceback (most recent call last):
#    File "<stdin>", line 1, in <module>
#    File "/usr/local/lib/python3.6/dist-packages/ribs/optimizers/_optimizer.py", line 61, in __init__
#      self._archive.initialize(self._solution_dim)
#    File "/usr/local/lib/python3.6/dist-packages/ribs/archives/_cvt_archive.py", line 204, in initialize
#      ArchiveBase.initialize(self, solution_dim)
#    File "/usr/local/lib/python3.6/dist-packages/ribs/archives/_archive_base.py", line 350, in initialize
#      self._occupied = np.zeros(self._storage_dims, dtype=bool)
#  TypeError: 'tuple' object cannot be interpreted as an integer
```

### Problem

In class `CVTArchive`, parameter `dims` is miscast into a tuple on line 101:
```
 ArchiveBase.__init__(
            self,
            storage_dims=(bins,), # <<<< HERE
            behavior_dim=len(ranges),
            seed=seed,
            dtype=dtype,
        )
```

### Solution

Use the same cast as in GridArchive on lines 41 and 48:
```
        self._dims = np.array(dims) # <<<< HERE
        if len(self._dims) != len(ranges):
            raise ValueError(f"dims (length {len(self._dims)}) and ranges "
                             f"(length {len(ranges)}) must be the same length")

        ArchiveBase.__init__(
            self,
            storage_dims=tuple(self._dims), # <<<< HERE
            behavior_dim=len(self._dims),
            seed=seed,
            dtype=dtype,
        )
```

**Comment by btjanaka** [comment]
Hi @twoletters , I'm not sure I understand your issue. The `bins` parameter to `CVTArchive` is intended to be an integer indicating how many cells to use when creating a centroidal voronoi tesselation.

**Comment by btjanaka** [comment]
If you're trying to discretize each dimension, perhaps `GridArchive` would be more suitable for your use case?

**Comment by twoletters** [comment]
I see. It looks like I misunderstood how CVTArchive works. Thank you!

**Comment by btjanaka** [comment]
Okay! Glad I could help. If you have not already, I suggest reading this paper: https://ieeexplore.ieee.org/document/8000667 It's the paper that we base the `CVTArchive` on.

**Comment by tehqin** [comment]
@twoletters The robot arm [tutorial](https://docs.pyribs.org/en/stable/tutorials/arm_repertoire.html) is a good usage reference for CVT archives. The tutorial includes how to use the visualization code as well.
