### ISSUE TITLE
[BUG] Lunar Lander Example does not work

### ISSUE THREAD

**Issue by Bam4d** [icaros-usc/pyribs#69]
- pyribs version: 0.2.1
- Python version: 3.8
- Operating System: Ubuntu 20.04

### Description

The `seaborn` dependency is not installed when using `pip install -e .[examples]`

This leads to the following error:
```
Traceback (most recent call last):
  File "lunar_lander.py", line 15, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
```

### Steps to Reproduce

1. Clone repository
2. run `pip install -e .[examples]` to install depedencies for examples
3. `cd examples`
4. python lunar_lander.py

**Comment by btjanaka** [comment]
Thanks for the bug report! The `lunar_lander.py` example is not currently functional (it's using MAP-Elites instead of CMA-ME). Would you mind referring to the tutorial for now? (https://docs.pyribs.org/en/latest/tutorials/lunar_lander.html)

**Comment by btjanaka** [comment]
I'll post here when I've gone through it (I'll go remove it for now actually).

**Comment by btjanaka** [comment]
@Bam4d should be good to go. Let me know if anything else fails :laughing:
